language: python

python:
 - "3.6"

script: pytest -v

notifications:
    slack: sandboxactvf:YrUAl7LnH5fxYsVoKqc2Yq1C
    email:
      recipients:
        - cary.e.riina@gmail.com
      on_success: always
      on_failure: always
